import type { Metadata } from 'next'
import './globals.css'
import { ReactNode } from 'react'
import ClientLayout from './client-layout'


export const metadata: Metadata = {
	title: 'SubSight',
	description: 'Generated by create next app',
	icons: {
		icon: '/favicon.svg',
	},
}

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang='en'>
			<body>
				<ClientLayout>{children}</ClientLayout>
			</body>
		</html>
	)
}
