import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import ReduxProvider from '@/components/providers/ReduxProvider'
import { ReactNode } from 'react'
import { Toaster } from '@/components/ui/sonner'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'SubSight',
	description: 'Generated by create next app',
	icons: {
		icon: '/favicon.svg',
	},
}

export default async function RootLayout({
	children,
}: Readonly<{ children: ReactNode }>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
                <ReduxProvider>
					{children}
				</ReduxProvider>
				<Toaster />
			</body>
		</html>
	)
}
